NEURAL NETWORKS

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("D:\demonic head\digit recog\\train.csv")
data.shape

(42000, 785)

In [ ]:
data=np.array(data)
m,n=data.shape
np.random.shuffle(data)

data_dev=data[0:1000].T
Y_dev=data_dev[0]
X_dev=data_dev[1:n]
X_dev=X_dev/255

data_train=data[1000:m].T
Y_train=data_train[0]
X_train=data_train[1:n]
X_train=X_train/255

Forward Propogation

In [ ]:
def init_params():
    w1=np.random.rand(10,784)-0.5
    b1=np.random.rand(10,1)-0.5
    w2=np.random.rand(10,10)-0.5
    b2=np.random.rand(10,1)-0.5
    return w1,b1,w2,b2

def ReLU(Z):
    return np.maximum(0,Z)

def softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))

def forward_prop(w1,b1,w2,b2,X):
    Z1=w1.dot(X)+b1
    A1=ReLU(Z1)
    Z2=w2.dot(A1)+b2
    A2=softmax(Z2)
    return Z1,Z2,A1,A2

Backward Propogation

In [ ]:
def deriv_ReLU(Z):
    return Z>0

def one_hot(Y):
    one_hot_y=np.zeros((Y.size,Y.max()+1))
    one_hot_y[np.arange(Y.size),Y]=1
    one_hot_Y=one_hot_y.T
    return one_hot_Y


def back_prop(Z1,A1,Z2,A2,w2,X,Y):
    # m=Y.size
    one_hot_Y=one_hot(Y)
    dZ2=A2-one_hot_Y
    dW2=(1/m)*(dZ2.dot(A1.T))
    dB2=(1/m)*(np.sum(dZ2))
    dZ1=w2.T.dot(dZ2)*deriv_ReLU(Z1)
    dW1=(1/m)*dZ1.dot(X.T)
    dB1=(1/m)*(np.sum(dZ1))
    return dW1,dW2,dB1,dB2

def update_params(dW1,dW2,dB1,dB2,alpha,w1,w2,b1,b2):
    w1=w1-alpha*dW1
    w2=w2-alpha*dW2
    b1=b1-alpha*dB1
    b2=b2-alpha*dB2
    return w1,w2,b1,b2


Gradient descent

In [ ]:
def get_predictions(A2):
    return np.argmax(A2,0)


def get_acc(predictions,Y):
    print(predictions,Y)
    return np.sum(predictions==Y)/Y.size


def gradient_desc(X,Y,alpha,Iterations):
    w1,b1,w2,b2=init_params()
    for i in range(Iterations):
        Z1,Z2,A1,A2=forward_prop(w1,b1,w2,b2,X)
        dW1,dW2,dB1,dB2=back_prop(Z1,A1,Z2,A2,w2,X,Y)
        w1,w2,b1,b2=update_params(dW1,dW2,dB1,dB2,alpha,w1,w2,b1,b2)
        if(i%10==0):
            print("Iteration:",i)
            predictions=get_predictions(A2)
            print("Accuracy:",get_acc(predictions,Y))
    return w1,b1,w2,b2

Training

In [ ]:
w1,b1,w2,b2=gradient_desc(X_train,Y_train,0.05,1000)

Iteration: 0
[1 8 1 ... 5 1 8] [2 3 0 ... 1 2 3]
Accuracy: 0.04290243902439025
Iteration: 10
[9 9 7 ... 2 4 8] [2 3 0 ... 1 2 3]
Accuracy: 0.094
Iteration: 20
[9 9 7 ... 2 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.13641463414634147
Iteration: 30
[6 2 7 ... 3 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.18434146341463414
Iteration: 40
[6 3 7 ... 3 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.23617073170731706
Iteration: 50
[6 3 0 ... 3 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.28485365853658534
Iteration: 60
[6 3 0 ... 3 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.3335365853658537
Iteration: 70
[6 3 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.378
Iteration: 80
[6 3 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.41536585365853657
Iteration: 90
[6 3 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.44909756097560977
Iteration: 100
[6 2 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.4795609756097561
Iteration: 110
[6 2 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.5079512195121951
Iteration: 120
[6 2 0 ... 1 6 1] [2 3 0 ... 1 2 3]
Accuracy: 0.5328048

In [ ]:
_,a,b,tester_1=forward_prop(w1,b1,w2,b2,X_dev)
predd=get_predictions(tester_1)
get_acc(predd,Y_dev)

[0 7 6 2 5 4 1 5 2 0 7 7 1 2 2 3 0 4 1 7 3 5 8 7 5 0 7 4 0 9 1 2 4 0 9 3 4
 0 6 8 9 4 1 6 3 5 1 0 0 1 1 3 7 7 2 9 1 2 8 8 9 1 8 5 8 0 2 4 1 1 3 6 6 8
 9 5 9 8 5 2 2 4 5 6 0 3 1 1 5 7 7 8 1 1 5 3 2 1 9 8 8 6 6 0 0 4 1 3 7 9 2
 7 5 8 5 8 6 1 3 3 9 0 9 1 8 6 0 8 4 4 4 3 4 5 2 9 0 3 1 0 9 1 4 2 1 4 9 3
 0 3 7 1 2 9 9 7 6 8 8 7 2 8 8 8 3 7 3 6 3 7 3 9 5 6 3 1 7 6 6 5 4 2 3 9 8
 0 7 5 0 1 6 3 7 5 8 5 1 6 6 0 5 3 6 1 0 2 0 3 3 9 9 4 0 3 3 5 1 4 0 4 7 0
 3 6 6 1 3 9 1 9 2 1 6 0 1 4 8 9 1 3 6 9 9 7 9 7 6 1 3 8 1 5 6 4 9 9 2 7 8
 3 7 8 6 6 6 4 3 1 1 0 1 7 7 6 2 1 0 9 5 8 5 1 0 4 0 5 6 3 8 4 6 9 0 6 8 8
 7 0 7 7 4 1 3 4 6 1 3 3 6 8 5 3 9 9 9 7 2 8 3 7 1 9 0 8 6 0 2 8 9 9 8 1 7
 8 6 3 7 8 1 4 6 9 0 7 2 4 7 9 5 8 4 7 4 6 9 4 2 5 2 6 9 6 8 8 2 7 2 1 5 0
 0 9 8 7 0 0 5 9 9 3 6 7 9 4 0 0 9 7 7 9 6 2 0 0 4 7 7 6 1 3 7 7 9 1 7 4 3
 6 6 9 8 1 6 4 8 0 2 9 2 9 5 3 9 8 6 4 4 2 6 1 9 7 9 8 9 9 5 4 3 9 8 9 1 7
 0 8 2 1 5 1 8 0 2 0 2 9 1 2 9 1 0 1 8 7 3 4 7 9 1 9 2 1 0 1 5 7 6 3 5 4 8
 5 7 2 8 4 6 9 1 6 5 8 5 

0.852

In [ ]:
tt=pd.read_csv("D:\demonic head\digit recog\\test.csv")
tester2=np.array(tt)
m,n=tester2.shape
np.random.shuffle(tester2)

tp=tester2.T
#Y2=tp[0].T
X2=tp
X2=X2/255

a,b,c,tester_2=forward_prop(w1,b1,w2,b2,X2)
preddd=get_predictions(tester_2)
print(preddd)
#get_acc(preddd,Y2)

[7 7 3 ... 6 6 3]
